server:
  port: 8082
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/bd_plazoleta?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: false

appDescription: "Pragma Powerup - Microservicio Plazoleta"
appVersion: "1.0.0"
